# Dockerfile.dev
FROM node:20

WORKDIR /app

# Copy deps first for speed
COPY package.json package-lock.json* ./
RUN npm install

# Copy rest of the app
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]