export const TITLE_STOP_PHRASES = [
  "can you",
  "could you",
  "would you",
  "please",
  "pls",
  "kindly",
  "explain",
  "explain to me",
  "teach me",
  "help me understand",
  "show me",
  "walk me through",
  "break down",
  "what is",
  "what's",
  "what are",
  "how do",
  "how does",
  "how to",
  "why is",
  "why are",
  "tell me",
  "give me",
  "in simple terms",
  "simply",
  "basically",
  "for beginners",
  "step by step",
  "with examples",
  "with an example",
  "for dummies",
  "quickly",
  "briefly",
  "i want to know",
  "i want to learn",
  "i need to know",
  "i am trying to understand",
  "i'm trying to understand",
  "i don't understand",
  "please explain",
  "thanks",
  "thank you"
]

export const LEADING_ARTICLES = ["the", "a", "an"];